### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [salemove/node-config_loader#4]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by indrekj** [comment]
Config Loader is being used to load configuration files on application start. This doesn't require high level of ops/sec. This library is currently very stable so we're not going to replace ejs at the moment.
